spring:
  application:
    name: Homework_Spring_Data_JPA_2
  datasource:
    url: jdbc:postgresql:///spring_data_jpa_h2
    username: postgres
    password: 1111@2222@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080
